@startuml
class EmployeeManager{
- {static} employeeList: ArrayList<Employee>
+ {static} add(Employee): void
+ {static} allEmployeesToString(): String
+ {static} getEmployeeById(int): Employee
}
class OrderQueue{
- OrdersInQueue: Queue<Order>
- DishesInProgress: LinkedList<Dish>
- DishesCompleted: Queue<Dish>
+ OrderQueue()
+ addOrderInQueue(Order): void
+ confirmOrdersInQueue(): void
+ dishCompleted(int): void
+ dishDelivered(int): void
+ queueIsEmpty(): boolean
}

class Employee{
- ID: int
+ Employee(int)
+ receiveIngredient(String , int): void
+ getID(): int
}
class ServiceEmployee {
- {static} orderQueue: OrderQueue
~ ServiceEmployee(int)
}
class Server{
+ Server(int)
+ takeSeat(Table): void
+ enterMenu(Table, Order): void
+ deliverDishCompleted(int): void
+ deliverDishFailed(int): void
+ printBill(Table): void
+ clearTable(Table): void
+ toString(): String
}
class Cook{
+ Cook(int)
+ orderReceived(): void
+ dishReady(int): void
+ toString(): String
}
class Manager{
+ Manager(int)
+ checkInventory(): void
+ toString(): String
}

Employee <|-- ServiceEmployee
ServiceEmployee <|-- Cook
ServiceEmployee <|-- Server
Employee <|-- Manager


abstract class Event{
~ employeeType: String
~ employeeID: int
~ methodName: String
~ parameters: ArrayList<String>
~ Event(line: String)
- parseEvent(line: String): void
~ {static} parseOrder(str: String): Order
- {static} parseDish(str: String): Dish
~ {abstract} process(): void
}

class EventManager{
- {static} FILE: String = "phase1/event/event.txt"
- eventQueue: Queue<Event>
+ EventManager()
+ readFile(): void
+ processEvents(): void
}

class ProcessableEvent{
~ ProcessableEvent(line: String)
~ process(): void
- processCookEvent(cook: Cook): void
- processManagerEvent(manager: Manager): void
- processServerEvent(server: Server): void
}

class EventReader{
- file: String
- lines: ArrayList<String>
~ EventReader(file: String)
~ readFile(eventQueue: Queue<Event>): void
- addLinesToQueue(lines: ArrayList<String>, eventQueue: Queue<Event>): void
}


class Dish{
- name: String
- ingredientsRequired: HashMap<String, Ingredient>
- dishNumber: int
- countDish: int
- cost: float
- isReady; boolean
- table: Table
+ adjustIngredient
+ updateIngredientsStock
+ assignDishToTable
+ getName
+ getCost
+ getTable
+ toString
+ addCostToTable
+ isCancelled
+ getDishNumber
+ assignDishNumber




Event <|-- ProcessableEvent

class RestaurantSystem{
}
@enduml